### ISSUE TITLE
Does not seem to work anymore with the latest version of Harvest

### ISSUE THREAD

**Issue by danielberez** [orestes/harvest-languages#11]
Hi, 
I realize that now harvest supports translations, but it does not allow for multiples languages like some clients in French and others in English.
And it seems like the plug-in is no longer working with the latest version of Harvest, if you can look into it 
I would really appreciate.

Thanks.

**Comment by danielberez** [comment]
I changed the line 7 from file harvest-languages.js from
    var selector = '#invoice_header > div > div:nth-child(2)';
To
   var selector = '#invoice_header > div:nth-child(2)';

And now the language is working

**Comment by orestes** [comment]
That's awesome @danielberez!
Feel free to make a PR and I'll merge it. 

I haven't used Harvest in the last couple of years so I have no way to test it but I trust you :)

 If I find some time to give this repo some love I'll automate it to create new releases automatically when PRs are merged.

**Comment by Nerian** [comment]
I tried that as well, working nicely 👍

**Comment by orestes** [comment]
Thank you both @danielberez @Nerian. I'm waiting on you @Nerian to add a new commit to #12 bumping the version so a new release will be published with your fix automatically when merging the PR.

**Comment by orestes** [comment]
Fixed by #12.
New release is being reviewed by Chrome Web Store and will be automatically updated.
