### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Harjo** [orestes/harvest-languages#6]
Document Title
Factuur

From
van

For
Factuur aan

Invoice ID
Factuurnummer

PO Number
Ordernummer

Issue Date
Factuurdatum

Due Date
Uiterste betaaldatum

Upon Receipt
Bij ontvangst

Tax
BTW

Tax2
BTW 

Discount
Korting

Subject
Onderwerp

Item Type
Type

Description
Omschrijving

Quantity
Aantal

Unit Price
Prijs per eenheid

Amount
otaal

Subtotal
Subtotaal

Amount Due
Totaal

Notes
Opmerkingen

Page [page] of [toPage]
Pagina [page] van [toPage]

File Attachments
Bijlagen

Payments
Betalingen

Retainer Payments
Voorschot

Pay Invoice
Betaal factuur

Invoice Link
Factuur link

Paid
Betaald

Client Message
Hartelijk dank voor uw betaling

**Comment by orestes** [comment]
Thanks for the proposal @Harjo  :)

I need a couple more translations for the estimates module. Would you be able to provide me with them?

```
{
  "estimates": {
    "profile_t_estimate":"Offering",
    "profile_t_from":"From",
    "profile_t_for":"For",
    "profile_t_id": "Invoice ID",
    "profile_t_po_number": "PO Number",
    "profile_t_issue_date": "Issue Date",
    "profile_t_tax": "V.A.T.",
    "profile_t_tax2": "",
    "profile_t_discount": "Discount",
    "profile_t_subject": "Subject",
    "profile_t_type": "Item Type",
    "profile_t_description": "Description",
    "profile_t_quantity": "Quantity",
    "profile_t_unit_price": "Unit Price",
    "profile_t_amount": "Amount",
    "profile_t_subtotal": "Subtotal",
    "profile_t_amount_due": "Amount Due",
    "profile_t_notes": "Notes",
    "profile_t_page_numbers": "Page [page] of [toPage]",
    "profile_t_file_attachments": "File attachments",
    "profile_t_estimate_link":"Click here to accept the estimate.",
    "profile_t_accept_estimate":"Accept estimate",
    "profile_t_decline_estimate":"Decline estimate",
    "profile_t_estimate_accepted": "I accept the estimate.",
    "profile_t_estimate_declined":"I do not accept the estimate.",
    "profile_t_email_subject":"Estimate #%estimate_id% from %company_name%"
  }
}
```

**Comment by Harjo** [comment]
Sure. Please find them below.

Op za 22 dec. 2018 23:14 schreef Orestes Carracedo <notifications@github.com
>:

> Thanks for the proposal @Harjo <https://github.com/Harjo> :)
>
> I need a couple more translations for the estimates module. Would you be
> able to provide me with them?
>
{

**Comment by orestes** [comment]
Updated in https://github.com/orestes/harvest-languages/commit/ca0576b65a2dd3709fe8b5e1d8d4b509b3963eb1 

Released on https://github.com/orestes/harvest-languages/releases/tag/v3.2.0

Published on Chrome Web Store https://chrome.google.com/webstore/detail/icnfiaaikmceeffekddmbjhgojnkppac

Thanks @Harjo !
